server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/java/ {
        proxy_pass http://backend-java:8080/;
    }

    location /api/python/ {
        proxy_pass http://backend-python:5000/;
    }
}
